import { z } from "zod";

const GENERATED_TABLE_MIN = 1;
const GENERATED_TABLE_MAX = 50;
const GENERATED_TRIGGER_KEYS = new Set([
  "pos.order_created",
  "kitchen.order_ready",
  "waiter.order_ready",
  "kitchen.sla_warning",
]);

export const SmartNotifPayloadSchema = z.object({
  tableNo: z.string().optional().nullable(),
  orderNo: z.string().optional().nullable(),
  customerName: z.string().optional().nullable(),
  itemName: z.string().optional().nullable(),
  channel: z.string().optional().nullable(),
});

export type SmartNotifPayload = z.infer<typeof SmartNotifPayloadSchema>;

export function buildSmartNotifMessage(
  triggerKey: string,
  payload: SmartNotifPayload
): string {
  const t = payload.tableNo ? `meja ${payload.tableNo}` : "";
  const o = payload.orderNo ? `, nomor ${payload.orderNo},` : "";
  
  // Use specific templating logic based on the checklist
  switch (triggerKey) {
    case "pos.order_created":
    case "order_new_kitchen":
    case "order_new_bar":
      if (t && o) return `Ding ding ding. Perhatian. Pesanan baru ${t}${o} telah masuk ke dapur.`;
      if (t) return `Ding ding ding. Perhatian. Pesanan baru ${t} telah masuk ke dapur.`;
      if (payload.orderNo) return `Ding ding ding. Perhatian. Pesanan baru nomor ${payload.orderNo} telah masuk ke dapur.`;
      return `Ding ding ding. Perhatian. Pesanan baru telah masuk ke dapur.`;

    case "kitchen.order_ready":
    case "order_ready":
      if (t && o) return `Ding ding ding. Pesanan ${t}${o} sudah siap diantar.`;
      if (t) return `Ding ding ding. Pesanan ${t} sudah siap diantar.`;
      if (payload.orderNo) return `Ding ding ding. Pesanan nomor ${payload.orderNo} sudah siap diantar.`;
      return `Ding ding ding. Ada pesanan siap diantar.`;

    case "waiter.order_ready":
    case "order_ready_deliver":
      if (t) return `Waiter. Pesanan ${t} siap diantar.`;
      return `Waiter. Ada pesanan siap diantar.`;

    case "kitchen.sla_warning":
      if (t && o) return `Perhatian dapur. Pesanan ${t}${o} telah melewati batas waktu layanan.`;
      if (t) return `Perhatian dapur. Pesanan ${t} telah melewati batas waktu layanan.`;
      return `Perhatian dapur. Ada pesanan yang telah melewati batas waktu layanan.`;

    // Fallbacks to default
    default:
      return `Perhatian. Notifikasi operasional.`;
  }
}

export function buildVoiceAssetPath(
  triggerKey: string,
  payload: SmartNotifPayload
): { publicUrl: string; hasPermanentAudio: boolean } {
  // Normalize triggerKey to match directories
  let normalizedTrigger = triggerKey;
  if (triggerKey === "order_new_kitchen" || triggerKey === "order_new_bar") normalizedTrigger = "pos.order_created";
  if (triggerKey === "order_ready") normalizedTrigger = "kitchen.order_ready";
  if (triggerKey === "order_ready_deliver") normalizedTrigger = "waiter.order_ready";

  const tableId = payload.tableNo?.match(/\d+/)?.[0] ?? "";
  const tableNumber = Number(tableId);
  const hasPermanentAudio =
    GENERATED_TRIGGER_KEYS.has(normalizedTrigger) &&
    Number.isInteger(tableNumber) &&
    tableNumber >= GENERATED_TABLE_MIN &&
    tableNumber <= GENERATED_TABLE_MAX;

  const filename = hasPermanentAudio ? `table-${tableNumber}.mp3` : "order-created.mp3";
  const publicUrl = `/audio/smart-notif/generated/${normalizedTrigger}/${filename}`;
  
  return { publicUrl, hasPermanentAudio };
}

export function resolveFallbackVoiceUrl(triggerKey: string): string {
  let fallbackFile = "general-alert.mp3";
  if (triggerKey.includes("pos") || triggerKey.includes("order_new")) fallbackFile = "order-created.mp3";
  if (triggerKey.includes("kitchen") || triggerKey.includes("order_ready")) fallbackFile = "kitchen-ready.mp3";
  if (triggerKey.includes("waiter")) fallbackFile = "waiter-ready.mp3";

  return `/audio/smart-notif/fallback/${fallbackFile}`;
}

export async function processSmartNotifTrigger(
  triggerKey: string,
  payload: SmartNotifPayload,
  settings?: { autoGenerateVoiceAsset?: boolean }
) {
  const message = buildSmartNotifMessage(triggerKey, payload);
  const { publicUrl, hasPermanentAudio } = buildVoiceAssetPath(triggerKey, payload);
  const chimeUrl = "/audio/smart-notif/chime/garage-station-chime.mp3";

  // Permanent files are generated by scripts/generate-smart-notif-audio.ts for tables 1-50.
  if (hasPermanentAudio) {
    return {
      message,
      audioUrl: publicUrl,
      audioSource: "permanent",
      chimeUrl,
      tableNo: payload.tableNo,
      orderNo: payload.orderNo,
    };
  }

  if (settings?.autoGenerateVoiceAsset) {
    console.warn(
      "[SmartNotif] Runtime auto-generate is disabled. Generate permanent MP3 with npm run voice:generate-smart-notif.",
    );
  }

  // Fallback
  return {
    message,
    audioUrl: resolveFallbackVoiceUrl(triggerKey),
    audioSource: "fallback",
    chimeUrl,
    tableNo: payload.tableNo,
    orderNo: payload.orderNo,
  };
}
