import "dotenv/config";

import { writeFile } from "node:fs/promises";
import path from "node:path";

import {
  getExecutiveTtsStatus,
  synthesizeExecutiveSpeech,
} from "@/lib/executive-tts";
import { isElevenLabsTtsEnabled } from "@/lib/elevenlabs-tts";

const VOICES_URL = "https://api.elevenlabs.io/v1/voices";

type ElevenLabsVoice = {
  voice_id: string;
  name: string;
  labels?: Record<string, string>;
};

async function listVoices(apiKey: string): Promise<ElevenLabsVoice[]> {
  const response = await fetch(VOICES_URL, {
    headers: { "xi-api-key": apiKey },
  });
  if (!response.ok) {
    throw new Error(`List voices failed (${response.status}).`);
  }
  const payload = (await response.json()) as { voices?: ElevenLabsVoice[] };
  return payload.voices ?? [];
}

function scoreIndonesianVoice(voice: ElevenLabsVoice) {
  const name = voice.name.toLowerCase();
  const lang = (voice.labels?.language ?? voice.labels?.accent ?? "").toLowerCase();
  let score = 0;
  if (lang.includes("id") || lang.includes("indones")) score += 4;
  if (/indonesia|indonesian|gadis|sari|ayu|putri|wanita|female/i.test(name)) score += 3;
  if (/female|woman/i.test(voice.labels?.gender ?? "")) score += 2;
  if (/male|man/i.test(voice.labels?.gender ?? "")) score -= 2;
  return score;
}

async function main() {
  const status = getExecutiveTtsStatus();
  console.log("Executive TTS status:");
  console.log(JSON.stringify(status, null, 2));

  const apiKey = process.env.ELEVENLABS_API_KEY?.trim() ?? "";
  if (!apiKey) {
    console.error("\nELEVENLABS_API_KEY kosong di .env.local");
    process.exitCode = 1;
    return;
  }

  console.log("\nMengambil daftar voice dari ElevenLabs…");
  const voices = await listVoices(apiKey);
  console.log(`Total voice di akun: ${voices.length}`);

  const ranked = [...voices].sort(
    (a, b) => scoreIndonesianVoice(b) - scoreIndonesianVoice(a),
  );
  const top = ranked.slice(0, 8);
  console.log("\nRekomendasi (urut skor Indonesia / wanita):");
  for (const voice of top) {
    console.log(
      `  - ${voice.name} | id=${voice.voice_id} | labels=${JSON.stringify(voice.labels ?? {})}`,
    );
  }

  const pick = ranked[0];
  if (!pick) {
    console.error("Tidak ada voice di akun.");
    process.exitCode = 1;
    return;
  }

  const configuredVoice = process.env.ELEVENLABS_VOICE_ID?.trim();
  const voiceId = configuredVoice || pick.voice_id;

  if (!configuredVoice) {
    console.log(`\nELEVENLABS_VOICE_ID belum di-set. Rekomendasi: ${pick.name}`);
    console.log(`voice_id: ${pick.voice_id}`);
    const envPath = path.join(process.cwd(), ".env.local");
    const block = [
      "",
      "# ElevenLabs CEO voice (generated by npm run voice:test-elevenlabs)",
      `ELEVENLABS_API_KEY="${apiKey}"`,
      `ELEVENLABS_VOICE_ID="${pick.voice_id}"`,
      'ELEVENLABS_MODEL_ID="eleven_multilingual_v2"',
      'ELEVENLABS_TTS_ENABLED="true"',
      'EDGE_TTS_ENABLED="true"',
      'EDGE_TTS_VOICE="id-ID-GadisNeural"',
      "",
    ].join("\n");
    await writeFile(envPath, block, { encoding: "utf8", flag: "a" });
    console.log(`\nDitambahkan ke ${envPath} — restart dev server.`);
  }

  if (!isElevenLabsTtsEnabled()) {
    process.env.ELEVENLABS_VOICE_ID = voiceId;
  }

  console.log("\nTes synthesize ElevenLabs…");
  const result = await synthesizeExecutiveSpeech(
    "Perhatian CEO GARAGE Coffee and Motor. Tes suara ElevenLabs berhasil. Bahasa Indonesia siap operasional.",
    "elevenlabs",
  );
  console.log(`OK — provider=${result.usedProvider}, bytes=${result.audio.byteLength}`);

  const outDir = path.join(process.cwd(), "exports", "voice-mp3");
  const outFile = path.join(outDir, "00-elevenlabs-tes-ceo.mp3");
  const { mkdir } = await import("node:fs/promises");
  await mkdir(outDir, { recursive: true });
  await writeFile(outFile, Buffer.from(result.audio));
  console.log(`MP3 sample: ${outFile}`);
}

main().catch((error) => {
  console.error(error instanceof Error ? error.message : error);
  process.exitCode = 1;
});
